export const ipcChannels = {
  bootstrap: 'desktop:bootstrap',
  createAccount: 'desktop:create-account',
  login: 'desktop:login',
  unlock: 'desktop:unlock',
  logout: 'desktop:logout',
  lock: 'desktop:lock',
  refresh: 'desktop:refresh',
  updateSettings: 'desktop:update-settings',
  createConversation: 'desktop:create-conversation',
  sendMessage: 'desktop:send-message',
  addActivity: 'desktop:add-activity',
  listMessages: 'desktop:list-messages',
  aiStreamChunk: 'ai:stream-chunk',
  confirmToolExecution: 'ai:confirm-tool-execution',
  listGemmaModels: 'ai:list-gemma-models',
  detectProviders: 'ai:detect-providers',
  getSystemInfo: 'ai:get-system-info',
  pullModel: 'ai:pull-model',
  pullModelProgress: 'ai:pull-model-progress',
  installOllama: 'ai:install-ollama',
  installDocker: 'ai:install-docker',
  installProgress: 'ai:install-progress',
  startOllamaServer: 'ai:start-ollama-server',
  startDockerDaemon: 'ai:start-docker-daemon',
  startDockerOllama: 'ai:start-docker-ollama',
  clearConversation: 'desktop:clear-conversation',
  deleteConversation: 'desktop:delete-conversation',
  showMainWindow: 'desktop:show-main-window',
  showCompactWindow: 'desktop:show-compact-window',
  quitApp: 'desktop:quit-app',
  listDirectory: 'fs:list-directory',
  updateChecking: 'update:checking',
  updateAvailable: 'update:available',
  updateNotAvailable: 'update:not-available',
  updateDownloadProgress: 'update:download-progress',
  updateDownloaded: 'update:downloaded',
  updateError: 'update:error',
  installUpdate: 'update:install',
} as const

export type IpcChannel = (typeof ipcChannels)[keyof typeof ipcChannels]
